--semana 2 de base de datos



SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID 
FROM OEHR_EMPLOYEES;



		----------------

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM	OEHR_EMPLOYEES
WHERE	DEPARTMENT_ID = 90;

		---------------

SELECT	EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM	OEHR_EMPLOYEES
WHERE	(HIRE_DATE > '12/31/2015');

-- WHERE	(HIRE_DATE >= '01/01/2016'); --EN SU DEFECTO TAMBIEN FUNCIONA DE LAMISMA MANERA

------

SELECT	EMPLOYEE_ID as 'cod_empleado', LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE LAST_NAME = 'Whalen';
--WHERE LAST_NAME = 'Whalen' OR FIRST_NAME= 'Whalen'; -- IRSE A LA SEGURA DE QUE SEA UN APELLIDO O NOMBRE

--------

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY
FROM OEHR_EMPLOYEES
WHERE SALARY >= 3000 AND SALARY <= 5000;

--TAMBIEN SE PUEDE HACER DE A SIGUENTE FORMA, USANDO BETWEEN

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY
FROM OEHR_EMPLOYEES
WHERE (SALARY BETWEEN 3000 AND 5000);

------------------


SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY, HIRE_DATE
FROM OEHR_EMPLOYEES
WHERE HIRE_DATE NOT BETWEEN '01/01/2015' AND '12/31/2020';


--------------------------


SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID = 90 OR DEPARTMENT_ID=100 OR DEPARTMENT_ID=50;
-- WHERE DEPARTMENT_ID IN (90, 100, 50) -- TAMBIEN SE PUEDE HACER ASI, EL IN FUNCIONA COMO UN '=' CON MAS DE 1 = 1 ELEMENTO COMPARABLE, 
										-- ASI PERIMETE UN COMPARABLE DE IQIERA Y CUETNOS QUIERA DERECHA, SOLO FUCNIONA CUANDO ES OR (COMPARCIONES DE IGUALDAD)

-----------------

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE MANAGER_ID <> 100 OR MANAGER_ID <> 120 OR MANAGER_ID <> 114 OR MANAGER_ID <> 121;
--WHERE MANAGER_ID NOT IT(100,120,114,121);


SELECT * 
FROM OEHR_EMPLOYEES
WHERE LAST_NAME LIKE 'S%a' OR LAST_NAME LIKE '%a'; 

SELECT *
FROM OEHR_EMPLOYEES
WHERE COMMISSION_PCT IS NULL;




