-------------------------------------------------------------
-- muestra las fechas son el 0 inicial ose "01" lo muestra como "1"

--TO_CAHR PASA DE NUMEROS A TEXTO
SELECT TO_CHAR(HIRE_DATE,'fnDD Month YYYY') from OEHR_EMPLOYEES;


-- asi se muestra la fecha normal "01"
SELECT TO_CHAR(HIRE_DATE,'DD Month YYYY') from OEHR_EMPLOYEES;



SELECT LENGTH(TO_CHAR(HIRE_DATE,'fmDD Month YYYY')) from OEHR_EMPLOYEES as largofm;

SELECT LENGTH(TO_CHAR(HIRE_DATE,'DD Month YYYY')) from OEHR_EMPLOYEES as largonormal;

----------------
--hacer este

SELECT TO_CHAR(HIRE_DATE,'fnDD Month YYYY') as CONFM,
TO_CHAR(HIRE_DATE,'DD Month YYYY') as SINFM, 
LENGTH(TO_CHAR(HIRE_DATE,'DD Month YYYY')), 
LENGTH(TO_CHAR(HIRE_DATE,'fmDD Month YYYY')) 
FROM OEHR_EMPLOYEES;


-----------mostar fecha acutaul en cieto fromato
SELECT TO_CHAR(SYSDATE,'DAY DDth MONTH "OF" YYYY')
FROM Dual;

------------visualmete hacerlo en español
SELECT TO_CHAR(SYSDATE,'DAY DD MONTH "de" YYYY', 'NLS_DATE_LANGUAGE=SPANISH')
FROM Dual;

-- PARA MOSTAR EL SALRIO DE UN CIERTO FROMARTO, LA CATIDAD DE 99 ES LA QUES EMOSTRARA
SELECT TO_CHAR(SALARY, '$99,999.99') AS SALARIO
FROM OEHR_EMPLOYEES;


---
SELECT EMPLOYEE_ID AS COD_EMPELADO, FIRST_NAME||' '|| LAST_NAME AS NOMBRE_COMPLETO,
EMAIL||'@DB.UCM.CL' AS EMAIL, TO_CHAR(SALARY, '$99,999.99') AS SALARIO
FROM OEHR_EMPLOYEES
ORDER BY SALARY DESC;


-- FROZAR QUE UN TEXTO PASE A NUMERO ES TO_NUMBER

SELECT TO_CHAR(SYSDATE,'YYYY') AS TEXTO
FROM Dual;


--- LA VERSION DE TEXTO Y LA VERISON A NUMERO DE LA FECHA
SELECT TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'),'9999') AS NUMERO, TO_CHAR(SYSDATE,'YYYY') AS TEXTO
FROM Dual;


-- DUMP PARA HACERLA UNA AUDITORIA A ESA DATA, ASI SABMOS QUE TIPO DE DATO ES Y TODO ESO
SELECT DUMP(TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'),'9999')) AS NUMERO, DUMP(TO_CHAR(SYSDATE,'YYYY')) AS TEXTO
FROM Dual;


---
SELECT TO_DATE('02-02-25', 'DD-MM-YY') FROM Dual;
----fx nos exige que tengamos el formato

SELECT TO_DATE('02-02-25', 'fxDD-MM-YY') FROM Dual;

----------
SELECT TO_DATE('01-01-49', 'DD-MM-YY') FROM Dual;