--CLASE 5 27-08-25
-- ONLINE

--HACER TAREA DURANTE CLASE Y MNADAR A FINAL DE LA CLASE AL CORREO DEL PROFE- EN PAREJA



--EJEMPLO FUNCIONES NUMERICAS
-- DUAL ES UNA BASE DE DATOPS INTERNA PARA PODER HACER PRUEBAS

SELECT ROUND(45.926,2), ROUND(45.926,0), ROUND(45.926,-1)
FROM dual;


SELECT ROUND(45.926,2), TRUNC(45.926), TRUNC(45.926,-1)
FROM dual;

SELECT LAST_NAME, SALARY, MOD(SALARY, 5000)
FROM OEHR_EMPLOYEES 
WHERE JOB_ID ='SA_REP';
----------------------------------------------------------------------
--ALGUNAS DE HORA

SELECT SYSDATE
FROM DUAL;

SELECT SYSTIMESTAMP
FROM DUAL;

-- con nuestra zona horaria
SELECT TO_CHAR(SYSTIMESTAMP -4/24,'DD-MM-YYYY hh:mm:ss')
FROM DUAL;



--------------------------------------------------
--FUNCIONES DE FECHAS

-- PARA PODER VER EL SIGUIENTE FECHA DE DIA, EN ESTE CASO EL DIA LUNES
SELECT NEXT_DAY(SYSDATE,'MONDAY')
FROM DUAL;

--MESES ENTRE LA FECHA ACTUAL Y LA FECHA INGRESADA
SELECT MONTHS_BETWEEN(SYSDATE,DATE '2025-01-01')
FROM DUAL;

--ULTIMO DIA DEL MES
SELECT LAST_DAY(SYSDATE) AS ULTIMO_DIA_DEL_MES
FROM DUAL;


-- AGREGAR MES O QUITAR MIES
SELECT ADD_MONTHS(SYSDATE,3)
FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,-3)
FROM DUAL;

--ROUND- LO APROXIMA AL MES MAS CERCA, COMO YA PSO LO 15 PRIMEROD IAS DEL MES PASA AL SIGUINETE
SELECT ROUND(DATE'2025-08-26','MONTH')
FROM DUAL;


--TRUNC LO HACE QUE ESTAMOS DENTRO DEL MES ASI QUE ME REGRESE ESE MISMO MES
SELECT TRUNC(DATE'2025-08-26','MONTH')
FROM DUAL;

------------------------------------------------