--TAREA EN CLASES (27/08/2025)
-- DAMIAN RODIRGUEZ ENCIANA

--EJERCICIO 1

SELECT EMPLOYEE_ID, UPPER(LAST_NAME) AS "APELLIDO",
LENGTH(LAST_NAME) AS "CANTIDAD DE CARACTERES"
FROM OEHR_EMPLOYEES ORDER BY LENGTH(LAST_NAME);


--EJERCICIO 2

SELECT EMPLOYEE_ID, LAST_NAME AS "APELLIDO", ROUND(SALARY,-1)AS "REDONDEADO",
TRUNC(SALARY,-1) AS "TRUNCADO"
FROM OEHR_EMPLOYEES;


--EJERCICIO 3

SELECT EMPLOYEE_ID, HIRE_DATE AS "FECHA DE CONTRATACIÓN", 
ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "MESES TRABAJADOS"
FROM OEHR_EMPLOYEES;


--EJERCICIO 4

SELECT EMPLOYEE_ID, FIRST_NAME||' '||FIRST_NAME AS "NOMBRE COMPLETO", 
HIRE_DATE AS "FECHA DE CONTRATACION",
ROUND((SYSDATE - HIRE_DATE)/7) AS "SEMANAS TRABAJADAS"
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IN (50,80)
ORDER BY "SEMANAS TRABAJADAS";
