-- TAREA1
-- QUISIERA VER LOS DATOS DE TODOS AQUELLOS DEPARTAMENTOS EN LOS QUE SU 
-- NOMBRE TENGA COMO SEGUNDA LETRA LA A Y TERMINE CON LA LETRA S

SELECT DEPARTMENT_NAME
FROM OEHR_DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '_a%s';

-- TAREA2
-- QUISIERA VER COD, NOMBRE Y APELLIDO CONCATENADOS, DE TODOS AQUELLOS
-- TRABAJADORES, DONDE SU CARGO TENGA COMO PENÚLTIMA LETRA LA A

SELECT  EMPLOYEE_ID ||' '||FIRST_NAME||' '||LAST_NAME, AS "COD, NOMBRE Y APELLIDO"
FROM OEHR_EMPLOYEES
WHERE JOB_ID LIKE '%A_';


-- TAREA3
-- QUISIERA VER COD, NOMBRE Y APELLIDO CONCATENADOS, DE TODOS AQUELLOS
-- TRABAJADORES, DONDE SU APELLIDO NO TENGA CONTENIDA LA LETRA A

SELECT  EMPLOYEE_ID ||' '||FIRST_NAME||' '||LAST_NAME AS "COD, NOMBRE Y APELLIDO"
FROM OEHR_EMPLOYEES
WHERE LAST_NAME NOT LIKE '%A%' AND LAST_NAME NOT LIKE '%a%';