--

CREATE TABLE DAMIAN_RODRIGUEZ(
    COD_USUARIO NUMBER,
    NOMBRE_USUARIO VARCHAR(25),
    APELLIDO1_USUARIO  VARCHAR (25),
    APELLIDO2_USUARIO VARCHAR (25),
    CONSTRAINT PK_DAMIAN_RODRIGUEZ PRIMARY KEY (COD_USUARIO)
);

INSERT INTO DAMIAN_RODRIGUEZ(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
    VALUES (1,"DAMIAN", "RODRIGUEZ", "ENCINA")





----
CREATE OR REPLACE PROCEDURE DR_CARGA_USURIOS(
    COD_USUARIO_P NUMBER,
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
) 
IS 
BEGIN
    INSERT INTO DAMIAN_RODRIGUEZ(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
    VALUES (COD_USUARIO_P, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);
END;

---EJECUCION DE PA, ESTA SUJENTOA UN BLOQUE

BEGIN
    DR_CARGA_USURIOS(1,"CARLOS", "CASTRO", "BUSTAMANTE");
    DR_CARGA_USURIOS(2,"MACARENA", "URBINA", "FIGUEROA");
    DR_CARGA_USURIOS(3, "MARCELA", "PEREZ", "BASTIAS");
    DR_CARGA_USURIOS(4, "DAMIAN", "RODRIGUEZ", "ENCINA");
END;