--- seciencia anombre mio que se encargue de maneajr la clave priamria que ira de x a 99999999, uncio de 
-- lugoi para llamrla modiifcaar el procedmiento 


---cALCULAR BIEN LO QUE SE OCUPARA 
CREATE SEQUENCE DARE_SECUENCIA

    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2500
    NOCYCLE;


CREATE OR REPLACE PROCEDURE DARE_CARGA_USUARIOS(
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2
) 
IS 
BEGIN
    LOCK TABLE DARE_USUARIO IN ROW EXCLUSIVE MODE;
    INSERT INTO DARE_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
    VALUES (DARE_SECUENCIA.NEXTVAL, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);
    COMMIT;
    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            RAISE_APPLICATION_ERROR(-6501, 'ERROR INTERNO PROGRAMA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010,'UPSI FALLE');
        ROLLBACK;
END;



--- NO ME FUNCIONA DE
BEGIN
    DELETE FROM DARE_USUARIO;
    DARE_CARGA_USUARIOS('CARLOS', 'CASTRO', 'BUSTAMANTE');
    DARE_CARGA_USUARIOS('MACARENA', 'URBINA', 'FIGUEROA');
    DARE_CARGA_USUARIOS('MARCELA', 'PEREZ', 'BASTIAS');
    DARE_CARGA_USUARIOS('DAMIAN', 'RODRIGUEZ', 'ENCINA');
END;





CREATE OR REPLACE FUNCTION DARE_OBTENER_SUELDO(
	COD_USUARIO_F NUMBER
)
RETURN NUMBER
IS
	SUELDO_OBTENIDO NUMBER :=0;
BEGIN
	SELECT SALARY INTO SUELDO_OBTENIDO
	FROM OEHR_EMPLOYEES
	WHERE EMPLOYEE_ID = COD_USUARIO_F;

	IF(SUELDO_OBTENIDO IS NULL)THEN
		SUELDO_OBTENIDO :=0;
	END IF;
    
	RETURN SUELDO_OBTENIDO;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			RETURN -1;
END;
