--- SEGUNDO DESAFÍO =)
-- CREAR UNA FUNCIÓN QUE SE ENCARGUE DE REALIZAR LA CARGA DE REGISTROS 
-- PARA LAS CLAVES PRIMARIAS DE CARACTER AUTOINCREMENTAL.

-- LUEGO MODIFICAR SU PROCEDIMIENTO ALMACENADO DE CARGA DE DATOS, 
-- INCORPORANDO DENTRO DE LA CARGA DE DATOS EL LLAMADO A LA 
-- FUNCIÓN QUE SE ENCARGUE DEL CAMPO PRIMARIO.

-- REALIZAR UN DELETE FROM A LA TABLA SIN RESTRICCIONES LIMPIARLA
-- Y LUEGO UN LLAMADO AL PROCEDIMIENTO ALMACENADO PARA LA CARGA 
-- DE 10 REGISTROS


--CREACION DE LA FUNCION
CREATE OR REPLACE FUNCTION DARE_CARGA_FUNCION
IS
BEGIN
END;


--MODIFICAION DEL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE DARE_CARGA_USUARIOS(
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
    CORREO_P VARCHAR2 DEFAULT NULL
) 
IS 
BEGIN
    LOCK TABLE DARE_USUARIO IN ROW EXCLUSIVE MODE;

    INSERT INTO DARE_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL)
    VALUES (DARE_SECUENCIA.NEXTVAL, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P, 
            DARE_GENERAR_CORREOS(NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P) );
    COMMIT;
    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            RAISE_APPLICATION_ERROR(-6501, 'ERROR INTERNO PROGRAMA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010,'UPSI FALLE');
        ROLLBACK;
END;

