-- PRIMER DESAFIO =/
-- SE REQUIERE MODIFICAR LA TABLA USUARIO A TRAVÉS DE CÓDIGO CON LA 
-- INSTRUCCIÓN ALTER TABLE, AGREGANDO UN CAMPO NUEVO QUE SERÁ EMAIL 
-- DE TIPO VARCHAR2 DE LARGO 50.

-- LUEGO CREARÁ UNA FUNCIÓN QUE SE ENCARGUE DE GENERAR LOS CORREOS 
-- ELECTRÓNICOS DE LA SIGUIENTE FORMA: PRIMERA Y SEGUNDA LETRA DEL 
-- NOMBRE, TERCERA Y CUARTA LETRA DEL PRIMER APELLIDO, SEGUIDO DE UN 
-- PUNTO Y EL SEGUNDO APELLIDO COMPLETO QUE TERMINE EN @TESTSQL.CL 

-- MODIFICAR SU PROCEDIMIENTO ALMACENADO DE CARGA DE DATOS, 
-- INCORPORANDO DENTRO DE LA CARGA DE DATOS EL CORREO 
-- LUEGO REALIZAR UN DELETE FROM A LA TABLA SIN 
-- RESTRICCIONES LIMPIARLA Y LUEGO UN LLAMADO AL PROCEDIMIENTO 
-- ALMACENADO PARA LA CARGA DE UN REGISTRO DONDE SE UTILICE LA 
-- FUNCIÓN.


ALTER TABLE DARE_USUARIO ADD EMAIL VARCHAR2(50);


--FUNCION PARA GGENERAR EL CORREO

CREATE OR REPLACE FUNCTION DARE_GENERAR_CORREOS(
    NOMBRE_USUARIO_F VARCHAR2,
    APELLIDO1_USUARIO_F VARCHAR2,
    APELLIDO2_USUARIO_F VARCHAR2

)
RETURN VARCHAR2
IS
    CORREO_GENERADO VARCHAR2(50);
BEGIN
   CORREO_GENERADO:= UPPER(SUBSTR(NOMBRE_USUARIO_F,1,2) || SUBSTR(APELLIDO1_USUARIO_F,3,2) || '.'|| APELLIDO2_USUARIO_F || '@TESTSQL.CL');
   RETURN CORREO_GENERADO;
END;


--MODIFIACION DE PROCEDIMIENTO ALAMCENADO DE CARGA DE DATOS


CREATE OR REPLACE PROCEDURE DARE_CARGA_USUARIOS(
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
    CORREO_P VARCHAR2 DEFAULT NULL
) 
IS 
BEGIN
    LOCK TABLE DARE_USUARIO IN ROW EXCLUSIVE MODE;

    INSERT INTO DARE_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL)
    VALUES (DARE_SECUENCIA.NEXTVAL, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P, 
            DARE_GENERAR_CORREOS(NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P) );
    COMMIT;
    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            RAISE_APPLICATION_ERROR(-6501, 'ERROR INTERNO PROGRAMA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010,'UPSI FALLE');
        ROLLBACK;
END;


--LLAMADO DEL PROCEDIMIENTO
BEGIN
    DELETE FROM DARE_USUARIO;
    DARE_CARGA_USUARIOS('DAMIAN','RODRIGUEZ','ENCINA');
    DARE_CARGA_USUARIOS('ANGELO','ALBORNOZ','CASTILLO');
    DARE_CARGA_USUARIOS('PATRICIO','GONSALEZ','GOMEZ');
END;

--VERIFICACION 
SELECT *
FROM DARE_USUARIO;