--- SEGUNDO DESAFÍO =)
-- CREAR UNA FUNCIÓN QUE SE ENCARGUE DE REALIZAR LA CARGA DE REGISTROS 
-- PARA LAS CLAVES PRIMARIAS DE CARACTER AUTOINCREMENTAL.

-- LUEGO MODIFICAR SU PROCEDIMIENTO ALMACENADO DE CARGA DE DATOS, 
-- INCORPORANDO DENTRO DE LA CARGA DE DATOS EL LLAMADO A LA 
-- FUNCIÓN QUE SE ENCARGUE DEL CAMPO PRIMARIO.

-- REALIZAR UN DELETE FROM A LA TABLA SIN RESTRICCIONES LIMPIARLA
-- Y LUEGO UN LLAMADO AL PROCEDIMIENTO ALMACENADO PARA LA CARGA 
-- DE 10 REGISTROS


--CREACION DE LA FUNCION  AUTOINCREMENTAL
CREATE OR REPLACE FUNCTION DARE_CARGA_FUNCION
RETURN NUMBER
IS
    CODIGO_USUARIO_F NUMBER;
    MAXIMO_CODIGO_F  NUMBER;
BEGIN

    SELECT MAX(COD_USUARIO) INTO MAXIMO_CODIGO_F
    FROM DARE_USUARIO;


    IF MAXIMO_CODIGO_F IS NULL THEN
        CODIGO_USUARIO_F := 1;
    ELSE
        CODIGO_USUARIO_F := MAXIMO_CODIGO_F + 1;  -- 
    END IF;

    RETURN CODIGO_USUARIO_F;  
END;


--MODIFICAION DEL PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE DARE_CARGA_USUARIOS(
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
    CORREO_P VARCHAR2 DEFAULT NULL
) 
IS 
BEGIN
    LOCK TABLE DARE_USUARIO IN ROW EXCLUSIVE MODE;

    INSERT INTO DARE_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO, EMAIL)
    VALUES (DARE_CARGA_FUNCION(), NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P, 
            DARE_GENERAR_CORREOS(NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P));
    COMMIT;
    EXCEPTION
        WHEN PROGRAM_ERROR THEN
            RAISE_APPLICATION_ERROR(-6501, 'ERROR INTERNO PROGRAMA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010,'UPSI FALLE');
        ROLLBACK;
END;

----INSERTAR LOS 10 DATOS

BEGIN
    DELETE FROM DARE_USUARIO;
    DARE_CARGA_USUARIOS('ALBERTO', 'MUÑOZ', 'RODRIGUEZ');
    DARE_CARGA_USUARIOS('MARIA', 'GONZALEZ', 'PEREZ');
    DARE_CARGA_USUARIOS('JUAN', 'PEREZ', 'LOPEZ');
    DARE_CARGA_USUARIOS('SOFIA', 'MARTINEZ', 'TORRES');
    DARE_CARGA_USUARIOS('CARLOS', 'LOPEZ', 'FERNANDEZ');
    DARE_CARGA_USUARIOS('CAMILA', 'TORRES', 'SOTO');
    DARE_CARGA_USUARIOS('DIEGO', 'FERNANDEZ', 'HERRERA');
    DARE_CARGA_USUARIOS('VALENTINA', 'SOTO', 'CASTRO');
    DARE_CARGA_USUARIOS('NICOLAS', 'HERRERA', 'GOMEZ');
    DARE_CARGA_USUARIOS('FERNANDA', 'CASTRO', 'RAMIREZ');
END;

BEGIN
DARE_CARGA_USUARIOS('DAMIAN','RODRIGUEZ', 'ENCINA');
END;


-- VERIFICAR

SELECT *
FROM DARE_USUARIO
ORDER BY COD_USUARIO;

