----------------------------------------------------------------------------------
----------------------------TAREA-------------------------------------------------

-- CÓMO PODRÍA GENERAR UN PROCEDIMIENTO INTEGRAL, QUE SE ENCARGUE DE REALIZAR
-- LAS 3 OPERACIONES DE LOS REQUERIMIENTOS ANTERIORES, ESTE DEBE INCLUIR
-- CONTROL DE CONCURRENCIA, COMO TAMBIÉN CONTROL Y MANEJO DE TRANSACCIONES.


CREATE OR REPLACE PROCEDURE DARE_IUD_USUARIO(
    INDICE_P VARCHAR2,
	COD_USUARIO_P NUMBER,
	NOMBRE_USUARIO_P VARCHAR2 DEFAULT NULL,
	APELLIDO1_USUARIO_P VARCHAR2 DEFAULT NULL,
	APELLIDO2_USUARIO_P VARCHAR2 DEFAULT NULL
)
IS
BEGIN
    LOCK TABLE DARE_USUARIO IN ROW EXCLUSIVE MODE;

    IF UPPER(INDICE_P) = 'I' THEN
        INSERT INTO DARE_USUARIO(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
            VALUES(COD_USUARIO_P, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);

    ELSIF UPPER(INDICE_P) = 'U' THEN
        UPDATE DARE_USUARIO
        SET NOMBRE_USUARIO = NOMBRE_USUARIO_P,
            APELLIDO1_USUARIO = APELLIDO1_USUARIO_P,
            APELLIDO2_USUARIO = APELLIDO2_USUARIO_P
        
        WHERE COD_USUARIO = COD_USUARIO_P;

    ELSIF UPPER(INDICE_P) = 'D' THEN
        DELETE FROM DARE_USUARIO
        WHERE COD_USUARIO = COD_USUARIO_P;
    END IF;

    COMMIT;
    -- EXCEPTION
    --     WHEN 
END;





-- EJECUCIÓN DEL PA PARA INSERTAR
BEGIN
	DELETE FROM DARE_USUARIO;
	DARE_IUD_USUARIO('i',1,'CARLOS','CASTRO','BUSTAMANTE');
	DARE_IUD_USUARIO('i',2,'JUAN','SOLER','GARCIA');
	DARE_IUD_USUARIO('I',3,'MACARENA', 'URBINA', 'FIGUEROA');
	DARE_IUD_USUARIO('I',4,'JOSE', 'REYES', 'CASTRO');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM DARE_USUARIO;

-- QUISIERA ACTUALIZAR LOS DATOS JUAN SOLER, YA QUE HAY UN ERROR EN SU APELLIDO2,
-- EL CUAL DEBE SER SEPÚLVEDA.

-- EJECUCIÓN DEL PA PARA ACTUALIZAR
BEGIN
	DARE_IUD_USUARIO('U',2,'JUAN','SOLER','SEPÚLVEDA');
END;

-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM DARE_USUARIO;


-- QUISIERA BORRAR LOS DATOS JUAN SOLER, YA QUE DESDE AHORA NO EXISTE
-- EN LA BASE DE DATOS

-- EJECUCIÓN DEL PA PARA BORRAR

BEGIN
	DARE_IUD_USUARIO('d',2);
END;
-- VALIDAR QUE FUNCIONA EL PA

SELECT * FROM DARE_USUARIO;