--Creacion de la tabla con mi nombre

CREATE TABLE DAMIAN_RODRIGUEZ(
    COD_USUARIO NUMBER,
    NOMBRE_USUARIO VARCHAR(25),
    APELLIDO1_USUARIO  VARCHAR (25),
    APELLIDO2_USUARIO VARCHAR (25),
    CONSTRAINT PK_DAMIAN_RODRIGUEZ PRIMARY KEY (COD_USUARIO)
);

INSERT INTO DAMIAN_RODRIGUEZ(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
    VALUES (1,"DAMIAN", "RODRIGUEZ", "ENCINA")





---- Creacion del prosedimiento para insertar datos
CREATE OR REPLACE PROCEDURE DR_CARGA_USURIOS(
    COD_USUARIO_P NUMBER,
    NOMBRE_USUARIO_P VARCHAR2,
    APELLIDO1_USUARIO_P VARCHAR2,
    APELLIDO2_USUARIO_P VARCHAR2,
) 
IS 
BEGIN
    INSERT INTO DAMIAN_RODRIGUEZ(COD_USUARIO, NOMBRE_USUARIO, APELLIDO1_USUARIO, APELLIDO2_USUARIO)
    VALUES (COD_USUARIO_P, NOMBRE_USUARIO_P, APELLIDO1_USUARIO_P, APELLIDO2_USUARIO_P);
END;

---EJECUCION DE PA, ESTA SUJENTOA UN BLOQUE
-- Ejecucion del prosedimiento

BEGIN
    DR_CARGA_USUARIOS(2, 'CARLOS', 'CASTRO', 'BUSTAMANTE');
    DR_CARGA_USUARIOS(3, 'MACARENA', 'URBINA', 'FIGUEROA');
    DR_CARGA_USUARIOS(4, 'MARCELA', 'PEREZ', 'BASTIAS');
    DR_CARGA_USUARIOS(5, 'DAMIAN', 'RODRIGUEZ', 'ENCINA');
END;





---------------------------------TAREA--------------------------------------------

-- SE SOLICITA UN PROCEDIMIENTO ALMACENADO QUE SE ENCARGUE DE MODIFICAR EL NOMBRE
-- Y LOS APELLIDOS DE LOS USUARIOS DE ACUERDO A SU CÓDIGO, DE NOMBRE 
-- MODIFICA_USUARIOS




CREATE OR REPLACE PROCEDURE DR_MODIFICA_USUARIOS(
    NOMBRE_USUARIO_P      VARCHAR2,
    APELLIDO1_USUARIO_P   VARCHAR2,
    APELLIDO2_USUARIO_P   VARCHAR2,
    COD_USUARIO_P         NUMBER
)
IS
BEGIN
    UPDATE DAMIAN_RODRIGUEZ
    SET NOMBRE_USUARIO     = NOMBRE_USUARIO_P,
        APELLIDO1_USUARIO  = APELLIDO1_USUARIO_P,
        APELLIDO2_USUARIO  = APELLIDO2_USUARIO_P
    WHERE COD_USUARIO = COD_USUARIO_P;
END;



----Ejecucion

BEGIN
	DR_MODIFICA_USUARIOS('JUAN','PEREZ','REYES',1);
END;




-- SE SOLICITA UN PROCEDIMIENTO ALMACENADO QUE SE ENCARGUE DE ELIMINAR USUARIOS
-- DE ACUERDO A SU CÓDIGO, DE NOMBRE ELIMINA_USUARIOS

CREATE OR REPLACE PROCEDURE DR_ELIMINA_USUARIOS(
    COD_USUARIO_P NUMBER
)
IS
BEGIN
    DELETE FROM DAMIAN_RODRIGUEZ
    WHERE COD_USUARIO = COD_USUARIO_P;
END;


---Ejecucion

BEGIN
	DR_ELIMINA_USUARIOS(1);
END;
