
CLASE 9
SELECT * 
FROM OEHR_EMPLOYEES
WHERE SALARY > 11000;

----SALARIO DE ABERL
SELECT SALARY
FROM OEHR_EMPLOYEES
WHERE UPPER(LAST_NAME) = 'ABEL';

--------- HACERLO CON SUBCONSULTA
SELECT * 
FROM OEHR_EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME) = 'ABEL');

----SIN ALIAS SOLO USANOD USING
---TAMBEIN SE PUEDE USAR CO NALIAS, PERO ESTAB NO ERA NESEARIO PORQUE LOS PARAMETROS NO SE PETIAN EN OTRAS TABLAS

SELECT EMPLOYEE_ID AS "COD_TRABAJDOR", LAST_NAME AS "APELLIDO", DEPARTMENT_NAME AS "DEPARTAMENTO", CITY AS "CIUDAD"
FROM OEHR_EMPLOYEES E JOIN OEHR_DEPARTMENTS D USING (DEPARTMENT_ID)
JOIN OEHR_LOCATIONS L USING(LOCATION_ID)
WHERE SALARY > (SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME) = 'WHALEN');



----REVIASARRR

SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_NAME, CITY
FROM OEHR_EMPLOYEES JOIN OEHR_DEPARTMENTS ON() 
JOIN OEHR_LOCATIONS ON()
WHERE SALARY BETWEEN(SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME)= 'NAYER') 
                    AND (SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME)='WHALEN')

-------------

SELECT E.LAST_NAME, J.JOB_TITLE, E.SALARY
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON(E.JOB_ID=J.JOB_ID)
WHERE E.JOB_ID = (CARGO_TAYLOR= SELECT JOB_ID FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME)='TYLOR')
AND SALARY >

CARGO_TAYLOR= SELECT JOB_ID FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME)='TYLOR'
SALARY_TYLOR= SELECT SALARY FROM OEHR_EMPLOYEES WHERE UPPER(LAST_NAME)='TYLOR'





