------------------------------------------

SELECT COUNT(*) FROM OEHR_EMPLOYEES;

----FORMA NO OPTIMA 

SELECT EMPLOYEE_ID AS COD_EMPELADO, CONCAT(FIRST_NAME, CONCAT(' ',LAST_NAME)) AS "NOMBRE COMPLETO",
 JOB_TITLE AS "CARGO", DEPARTMENT_NAME AS "DEPARTAMNETO"
FROM OEHR_EMPLOYEES, OEHR_JOBS, OEHR_DEPARTMENTS;

-----FORMA CORRECTA ULITILZADO JOIN
-- MI FORMA

SELECT EMPLOYEE_ID AS COD_EMPELADO, CONCAT(FIRST_NAME, CONCAT(' ',LAST_NAME)) AS "NOMBRE COMPLETO",
 JOB_TITLE AS "CARGO", DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES JOIN OEHR_JOBS ON(OEHR_EMPLOYEES.JOB_ID = OEHR_JOBS.JOB_ID)
JOIN OEHR_DEPARTMENTS ON (OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID);


--- FORMA PROFE
--PONER SIMPRE EN TODAS LAS LAUSILAS DE DONDE ES EL ATRIBUTO DE LA TABLA


SELECT OEHR_EMPLOYEES.EMPLOYEE_ID AS "COD_EMPELADO", CONCAT(OEHR_EMPLOYEES.FIRST_NAME, CONCAT(' ',OEHR_EMPLOYEES.LAST_NAME)) AS "NOMBRE COMPLETO",
 OEHR_JOBS.JOB_TITLE AS "CARGO", OEHR_DEPARTMENTS.DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES JOIN OEHR_JOBS ON(OEHR_EMPLOYEES.JOB_ID = OEHR_JOBS.JOB_ID)
JOIN OEHR_DEPARTMENTS ON (OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID);


-------
---HACERLA CON ALIAS EN VEZ DEL NOMBRE COMPLETO, ESOT SE DEINE EN EL FROM

SELECT E.EMPLOYEE_ID AS COD_EMPELADO, CONCAT(E.FIRST_NAME, CONCAT(' ',E.LAST_NAME)) AS "NOMBRE COMPLETO",
 J.JOB_TITLE AS "CARGO", D.DEPARTMENT_NAME AS "DEPARTAMENTO"
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON(E.JOB_ID =J.JOB_ID)
JOIN OEHR_DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);


------ DE EMPLOYEES A REGION (VUELTA LARGA )
--VER NO FUNCIONA
SELECT E.EMPLOYEE_ID AS "COD_EMPLEADO", E.LAST_NAME AS "APELLIDO_EMPLEADO", R.REGION_NAME AS "NOMBRE_CONTINENTE"
FROM OEHR_EMPLOYEES E JOIN OEHR_DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN OEHR_LOCATION L ON (D.LOCATION_ID = L.LOCATION_ID)
JOIN OEHR_COUNTRIES CO ON (L.COUNTRY_ID = CO.COUNTRY_ID) 
JOIN OEHR_REGIONS R ON (CO.REGION_ID = R.REGION_ID);


---..

SELECT E.EMPLOYEE_ID AS "COD_EMPELADO", UPPER(CONCAT(E.FIRST_NAME, CONCAT(' ES ',CONCAT( J.JOB_ID, '_UCM_')))) AS "DATO CONCATENADO", J.JOB_TITLE AS "CARGO"
FROM OEHR_EMPLOYEES E JOIN OEHR_JOBS J ON (E.JOB_ID = J.JOB_ID);

--
SELECT * 
FROM OEHR_EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;


