--clase n4 creo
--Funciones SQL

-- VER CONCATENADO Y EN MAYUSCULAS
SELECT EMPLOYEE_ID, UPPER(FIRST_NAME||''|| LAST_NAME) AS "NOMBRE", UPPER(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;


--VER CONCATENADOS Y EN MINUSCULAS
SELECT EMPLOYEE_ID, LOWER(FIRST_NAME||' '|| LAST_NAME) AS "NOMBRE", LOWER(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;

-- VER CONCATENADO TODO CON SU PRIMERA LETRA EN MAYUSCULA (INITCAP SOLO ESTA DIPONIBLE EN ORACLE, NO DE FOMRA NATIVA EN MYSQL)
SELECT EMPLOYEE_ID, INITCAP(FIRST_NAME||' '|| LAST_NAME) AS "NOMBRE", INITCAP(EMAIL) AS "EMAIL"
FROM OEHR_EMPLOYEES;

--HACER, NO LA TERMINE, SESUPONE QUE LA FUCNION DEBERIA IR EN EL WHERE

--MOSTARR COD, NOMBRE, APELLIDO, CARGO Y DEPARTAMENTO DE LA EMPLEDA WHALEN



SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM OEHR_EMPLOYEES
WHERE UPPER(LAST_NAME) = 'WHALEN' OR UPPER(FIRST_NAME)='WHALEN';

------------------------------------------------------------------------------





-- QUISIERA VER ID, NOMBRE Y APELLIDO CONCATTENADO Y CORREO DE TODOS LOS TRBAJADORE, TODO EN MAYUCULAS UTILIZANDO LA FUNCION CONCATENAR


SELECT EMPLOYEE_ID, UPPER(CONCAT(FIRST_NAME, LAST_NAME)) AS "NOMBRES", UPPER(EMAIL) AS "CORREO"
FROM OEHR_EMPLOYEES;

--PROFE
SELECT EMPLOYEE_ID, UPPER(CONCAT(FIRST_NAME, CONCAT(' ', LAST_NAME))) AS "NOMBRE", EMAIL
FROM OEHR_EMPLOYEES;




---HGACER BIEN NO FUCNIONA

--QUISIERA QUE CORTARAN LA PENULTIMA LETRA DE CADA CORREO, ESTOA PLICA PARA QUE EL EL PEMPELDO APLICA PARA CADA EMPLEADO Y LUEGO DEBEN CONCATENARLA CON @SQL.CL

SELECT SUBSTR(EMAIL, 1 ,(LENGTH(EMAIL)-2)) || SUBSTR(EMAIL, LENGTH(EMAIL), LENGTH(EMAIL))|| '@SQL.CL' AS "CORREO CREADO", EMAIL
FROM OEHR_EMPLOYEES;



--QUISIERA MOSTARR UN CORREO ELECTRONICO PARA TRANAJAR QIE MANTEGA LA SIGUIENTE PATRON: PRIMERA LETRA DEL NOMBRE, CONCATENAMOS CON EL APELLIDO Y TODO LO ANTERIOR CONCATENADO CON @SQL.CL


SELECT UPPER(CONCAT(SUBSTR(FIRST_NAME),1,1), CONCAT(LAST_NAME,'@SQL.CL'))) AS "EMAIL"
FROM OEHR_EMPLOYEES;
