--DAMIAN RODRIGUEZ
----------------------------TAREA------------------------------------------------
-- QUISIERA SABER COD_TRABAJADOR, APELLIDO DE TRABAJADOR, NOMBRE DEL DEPARTAMENTO ASOCIADO,
-- Y EN CASO DE NO ESTAR ASOCIADO A UN DEPARTAMENTO, EL TRABAJADOR DEBE MOSTRARSE IGUAL.

SELECT E.EMPLOYEE_ID AS "COD_TRABAJADOR", E.LAST_NAME AS "APELLIDO", D.DEPARTMENT_NAME AS "DEPARTAMENTO ASOCIADO"
FROM OEHR_EMPLOYEES E LEFT JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID);


-- QUISIERA SABER DEL TRABAJADOR: NOMBRE CONCATENADO CON EL APELLIDO, SU CÓDIGO, 
-- EL NOMBRE DE SU DEPARTAMENTO ASOCIADO Y EL NOMBRE DEL JEFE ASOCIADO A DICHO
-- DEPARTAMENTO ADEMÁS DE LA CIUDAD EN LA QUE SE ENCUENTRA Y ADEMÁS DEL NOMBRE 
-- DE SU CARGO.

SELECT  E.EMPLOYEE_ID AS "CODIGO", CONCAT(E.FIRST_NAME,CONCAT(' ', E.LAST_NAME)) AS "NOMBRE", 
DEPARTMENT_NAME AS "DEPARTAMENTO",
 CONCAT(N.FIRST_NAME,CONCAT(' ', N.LAST_NAME)) AS "NOMBRE JEFE",
 L.CITY AS "CIUDAD",
 J.JOB_TITLE AS "CARGO"
FROM OEHR_EMPLOYEES E LEFT JOIN OEHR_DEPARTMENTS D ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID) 
LEFT JOIN OEHR_EMPLOYEES N ON(D.MANAGER_ID = N.EMPLOYEE_ID) 
LEFT JOIN OEHR_LOCATIONS L ON(D.LOCATION_ID =  L.LOCATION_ID) 
LEFT JOIN OEHR_JOBS J ON(E.JOB_ID = J.JOB_ID);